// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyDiet.Core.Infrastructure.Models;

public partial class CalendarMeal
{
    public int Id { get; set; }

    public int? CalendarEntryId { get; set; }

    public int? MealId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public Guid? UserId { get; set; }

    public virtual CalendarEntry CalendarEntry { get; set; }

    public virtual Meal Meal { get; set; }

    public virtual ICollection<MealSwap> MealSwapCalendarMeal { get; set; } = new List<MealSwap>();

    public virtual ICollection<MealSwap> MealSwapSwappedCalendarMeal { get; set; } = new List<MealSwap>();

    public virtual CoreUser User { get; set; }
}