// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyDiet.Core.Infrastructure.Models;

public partial class CalendarEntry
{
    public int Id { get; set; }

    public Guid? UserId { get; set; }

    public int? PlanId { get; set; }

    public DateOnly Date { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<CalendarMeal> CalendarMeal { get; set; } = new List<CalendarMeal>();

    public virtual Plan Plan { get; set; }

    public virtual CoreUser User { get; set; }
}