// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyDiet.Shared.Infrastructure.Models;

public partial class CoreUser
{
    public Guid Id { get; set; }

    public string Username { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<CalendarEntry> CalendarEntry { get; set; } = new List<CalendarEntry>();

    public virtual ICollection<Diet> Diet { get; set; } = new List<Diet>();
}