// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyDiet.Shared.Infrastructure.Models;

public partial class Diet
{
    public int Id { get; set; }

    public Guid UserId { get; set; }

    public string Name { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Plan> Plan { get; set; } = new List<Plan>();

    public virtual CoreUser User { get; set; }
}