// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

<<<<<<<< HEAD:src/Infrastructures/MyDiet.Core.Infrastructure/Models/Food.cs
namespace MyDiet.Core.Infrastructure.Models;
========
namespace MyDiet.Shared.Infrastructure.Models;
>>>>>>>> origin/dev:src/Infrastructures/MyDiet.Shared.Infrastructure/Models/Food.cs

public partial class Food
{
    public int Id { get; set; }

    public string Name { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<FoodAlternative> FoodAlternativeAlternativeFood { get; set; } = new List<FoodAlternative>();

    public virtual ICollection<FoodAlternative> FoodAlternativeFood { get; set; } = new List<FoodAlternative>();

    public virtual ICollection<MealFood> MealFood { get; set; } = new List<MealFood>();
}