// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyDiet.Core.Infrastructure.Models;

public partial class FoodAlternative
{
    public int Id { get; set; }

    public int? FoodId { get; set; }

    public int? AlternativeFoodId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Food AlternativeFood { get; set; }

    public virtual Food Food { get; set; }
}