// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

<<<<<<<< HEAD:src/Infrastructures/MyDiet.Core.Infrastructure/Models/MealSwap.cs
namespace MyDiet.Core.Infrastructure.Models;
========
namespace MyDiet.Shared.Infrastructure.Models;
>>>>>>>> origin/dev:src/Infrastructures/MyDiet.Shared.Infrastructure/Models/MealSwap.cs

public partial class MealSwap
{
    public int Id { get; set; }

    public int CalendarMealId { get; set; }

    public int SwappedCalendarMealId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual CalendarMeal CalendarMeal { get; set; }

    public virtual CalendarMeal SwappedCalendarMeal { get; set; }
}