// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

<<<<<<<< HEAD:src/Infrastructures/MyDiet.Core.Infrastructure/Models/Meal.cs
namespace MyDiet.Core.Infrastructure.Models;
========
namespace MyDiet.Shared.Infrastructure.Models;
>>>>>>>> origin/dev:src/Infrastructures/MyDiet.Shared.Infrastructure/Models/Meal.cs

public partial class Meal
{
    public int Id { get; set; }

    public int PlanId { get; set; }

    public int MealTypeId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<CalendarMeal> CalendarMeal { get; set; } = new List<CalendarMeal>();

    public virtual ICollection<MealFood> MealFood { get; set; } = new List<MealFood>();

    public virtual MealType MealType { get; set; }

    public virtual Plan Plan { get; set; }
}