// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

<<<<<<<< HEAD:src/Infrastructures/MyDiet.Core.Infrastructure/Models/MealType.cs
namespace MyDiet.Core.Infrastructure.Models;
========
namespace MyDiet.Shared.Infrastructure.Models;
>>>>>>>> origin/dev:src/Infrastructures/MyDiet.Shared.Infrastructure/Models/MealType.cs

public partial class MealType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Meal> Meal { get; set; } = new List<Meal>();
}