// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MyDiet.Core.Infrastructure.Models;

public partial class MyDietCoreDbContext : DbContext
{
    public MyDietCoreDbContext(DbContextOptions<MyDietCoreDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CalendarEntry> CalendarEntry { get; set; }

    public virtual DbSet<CalendarMeal> CalendarMeal { get; set; }

    public virtual DbSet<CoreUser> CoreUser { get; set; }

    public virtual DbSet<Diet> Diet { get; set; }

    public virtual DbSet<Food> Food { get; set; }

    public virtual DbSet<FoodAlternative> FoodAlternative { get; set; }

    public virtual DbSet<Meal> Meal { get; set; }

    public virtual DbSet<MealFood> MealFood { get; set; }

    public virtual DbSet<MealSwap> MealSwap { get; set; }

    public virtual DbSet<MealType> MealType { get; set; }

    public virtual DbSet<Plan> Plan { get; set; }

    public virtual DbSet<UnitConversion> UnitConversion { get; set; }

    public virtual DbSet<UnitOfMeasurement> UnitOfMeasurement { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CalendarEntry>(entity =>
        {
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.Plan).WithMany(p => p.CalendarEntry)
                .HasForeignKey(d => d.PlanId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_CalendarEntry_Plan");

            entity.HasOne(d => d.User).WithMany(p => p.CalendarEntry)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_CalendarEntry_User");
        });

        modelBuilder.Entity<CalendarMeal>(entity =>
        {
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.CalendarEntry).WithMany(p => p.CalendarMeal)
                .HasForeignKey(d => d.CalendarEntryId)
                .HasConstraintName("FK_CalendarMeal_CalendarEntry");

            entity.HasOne(d => d.Meal).WithMany(p => p.CalendarMeal)
                .HasForeignKey(d => d.MealId)
                .HasConstraintName("FK_CalendarMeal_Meal");

            entity.HasOne(d => d.User).WithMany(p => p.CalendarMeal)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_CalendarMeal_CoreUser");
        });

        modelBuilder.Entity<CoreUser>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
            entity.Property(e => e.Username)
                .HasMaxLength(50)
                .IsFixedLength();
        });

        modelBuilder.Entity<Diet>(entity =>
        {
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .IsFixedLength();
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.User).WithMany(p => p.Diet)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Diet_User");
        });

        modelBuilder.Entity<Food>(entity =>
        {
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .IsFixedLength();
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
        });

        modelBuilder.Entity<FoodAlternative>(entity =>
        {
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.AlternativeFood).WithMany(p => p.FoodAlternativeAlternativeFood)
                .HasForeignKey(d => d.AlternativeFoodId)
                .HasConstraintName("FK_FoodAlternative_AltFood");

            entity.HasOne(d => d.Food).WithMany(p => p.FoodAlternativeFood)
                .HasForeignKey(d => d.FoodId)
                .HasConstraintName("FK_FoodAlternative_Food");
        });

        modelBuilder.Entity<Meal>(entity =>
        {
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.MealType).WithMany(p => p.Meal)
                .HasForeignKey(d => d.MealTypeId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Meal_MealType");

            entity.HasOne(d => d.Plan).WithMany(p => p.Meal)
                .HasForeignKey(d => d.PlanId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Meal_Plan");

            entity.HasOne(d => d.User).WithMany(p => p.Meal)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Meal_CoreUser");
        });

        modelBuilder.Entity<MealFood>(entity =>
        {
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.Quantity).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.Food).WithMany(p => p.MealFood)
                .HasForeignKey(d => d.FoodId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_MealFood_Food");

            entity.HasOne(d => d.Meal).WithMany(p => p.MealFood)
                .HasForeignKey(d => d.MealId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_MealFood_Meal");

            entity.HasOne(d => d.UnitOfMeasurement).WithMany(p => p.MealFood)
                .HasForeignKey(d => d.UnitOfMeasurementId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_MealFood_UoM");

            entity.HasOne(d => d.User).WithMany(p => p.MealFood)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_MealFood_CoreUser");
        });

        modelBuilder.Entity<MealSwap>(entity =>
        {
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.CalendarMeal).WithMany(p => p.MealSwapCalendarMeal)
                .HasForeignKey(d => d.CalendarMealId)
                .HasConstraintName("FK_MealSwap_CalendarMeal");

            entity.HasOne(d => d.SwappedCalendarMeal).WithMany(p => p.MealSwapSwappedCalendarMeal)
                .HasForeignKey(d => d.SwappedCalendarMealId)
                .HasConstraintName("FK_MealSwap_Swapped");

            entity.HasOne(d => d.User).WithMany(p => p.MealSwap)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_MealSwap_CoreUser");
        });

        modelBuilder.Entity<MealType>(entity =>
        {
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .IsFixedLength();
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
        });

        modelBuilder.Entity<Plan>(entity =>
        {
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .IsFixedLength();
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.Diet).WithMany(p => p.Plan)
                .HasForeignKey(d => d.DietId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Plan_Diet");

            entity.HasOne(d => d.User).WithMany(p => p.Plan)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Plan_CoreUser");
        });

        modelBuilder.Entity<UnitConversion>(entity =>
        {
            entity.Property(e => e.ConversionFactor).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.FromUnit).WithMany(p => p.UnitConversionFromUnit)
                .HasForeignKey(d => d.FromUnitId)
                .HasConstraintName("FK_UnitConversion_FromUoM");

            entity.HasOne(d => d.ToUnit).WithMany(p => p.UnitConversionToUnit)
                .HasForeignKey(d => d.ToUnitId)
                .HasConstraintName("FK_UnitConversion_ToUoM");
        });

        modelBuilder.Entity<UnitOfMeasurement>(entity =>
        {
            entity.Property(e => e.Abbreviation)
                .IsRequired()
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .IsFixedLength();
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}