// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

<<<<<<<< HEAD:src/Infrastructures/MyDiet.Core.Infrastructure/Models/Plan.cs
namespace MyDiet.Core.Infrastructure.Models;
========
namespace MyDiet.Shared.Infrastructure.Models;
>>>>>>>> origin/dev:src/Infrastructures/MyDiet.Shared.Infrastructure/Models/Plan.cs

public partial class Plan
{
    public int Id { get; set; }

    public int DietId { get; set; }

    public string Name { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<CalendarEntry> CalendarEntry { get; set; } = new List<CalendarEntry>();

    public virtual Diet Diet { get; set; }

    public virtual ICollection<Meal> Meal { get; set; } = new List<Meal>();
}