// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyDiet.Core.Sql.Models.Models;

public partial class MealFood
{
    public int Id { get; set; }

    public int MealId { get; set; }

    public int FoodId { get; set; }

    public decimal Quantity { get; set; }

    public int UnitOfMeasurementId { get; set; }

    public byte[] CreatedAt { get; set; }

    public byte[] UpdatedAt { get; set; }

    public virtual Food Food { get; set; }

    public virtual Meal Meal { get; set; }

    public virtual UnitOfMeasurement UnitOfMeasurement { get; set; }
}