// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyDiet.Core.Sql.Models.Models;

public partial class Plan
{
    public int Id { get; set; }

    public int DietId { get; set; }

    public string Name { get; set; }

    public byte[] CreatedAt { get; set; }

    public byte[] UpdatedAt { get; set; }

    public virtual ICollection<CalendarEntry> CalendarEntry { get; set; } = new List<CalendarEntry>();

    public virtual Diet Diet { get; set; }

    public virtual ICollection<Meal> Meal { get; set; } = new List<Meal>();
}