// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyDiet.Core.Sql.Models.Models;

public partial class UnitConversion
{
    public int Id { get; set; }

    public int FromUnitId { get; set; }

    public int ToUnitId { get; set; }

    public decimal ConversionFactor { get; set; }

    public byte[] CreatedAt { get; set; }

    public byte[] UpdatedAt { get; set; }

    public virtual UnitOfMeasurement FromUnit { get; set; }

    public virtual UnitOfMeasurement ToUnit { get; set; }
}