// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyDiet.Core.Sql.Models.Models;

public partial class User
{
    public Guid Id { get; set; }

    public string Username { get; set; }

    public string Email { get; set; }

    public string HashedPassword { get; set; }

    public byte[] CreatedAt { get; set; }

    public byte[] UpdateAt { get; set; }

    public virtual ICollection<CalendarEntry> CalendarEntry { get; set; } = new List<CalendarEntry>();

    public virtual ICollection<Diet> Diet { get; set; } = new List<Diet>();
}