// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyDiet.Shared.Infrastructure.Models;

public partial class Food
{
    public int Id { get; set; }

    public string Name { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<FoodAlternative> FoodAlternativeAlternativeFood { get; set; } = new List<FoodAlternative>();

    public virtual ICollection<FoodAlternative> FoodAlternativeFood { get; set; } = new List<FoodAlternative>();

    public virtual ICollection<MealFood> MealFood { get; set; } = new List<MealFood>();
}