// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyDiet.Shared.Infrastructure.Models;

public partial class MealSwap
{
    public int Id { get; set; }

    public int CalendarMealId { get; set; }

    public int SwappedCalendarMealId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual CalendarMeal CalendarMeal { get; set; }

    public virtual CalendarMeal SwappedCalendarMeal { get; set; }
}