// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyDiet.Shared.Infrastructure.Models;

public partial class UnitOfMeasurement
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Abbreviation { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<MealFood> MealFood { get; set; } = new List<MealFood>();

    public virtual ICollection<UnitConversion> UnitConversionFromUnit { get; set; } = new List<UnitConversion>();

    public virtual ICollection<UnitConversion> UnitConversionToUnit { get; set; } = new List<UnitConversion>();
}