using BaseUtility;
using MyDiet.Core.Domain.Dtos.Diet;
using MyDiet.Core.Infrastructure.Models;

namespace MyDiet.Core.Business.Mappers
{
    internal class DietMapper : IMapper<Diet, DietDto>, IMapper<DietDto, Diet>, IMapper<CreateDietRequest, DietDto>
    {
        public Diet Map(DietDto input)
        {
            return new Diet
            {
                Id = input.Id,
                UserId = input.UserId,
                Name = input.Name,
                CreatedAt = input.CreatedAt,
                UpdatedAt = input.UpdatedAt
            };
        }

        public DietDto Map(Diet input)
        {
            return new DietDto
            {
                Id = input.Id,
                UserId = (Guid)input.UserId,
                Name = input.Name,
                CreatedAt = input.CreatedAt,
                UpdatedAt = input.UpdatedAt
            };
        }

        DietDto IMapper<CreateDietRequest, DietDto>.Map(CreateDietRequest input)
        {
            return new DietDto
            {
                Id = 0, // Assuming Id is autogenerated
                Name = input.Name,
            };
        }
    }
}
