using BaseUtility;
using MyDiet.Core.Domain.Dtos;
using MyDiet.Core.Domain.Dtos.Requests;
using MyDiet.Shared.Domain.Dtos;
using MyDiet.Shared.Infrastructure.Models;

namespace MyDiet.Shared.Business.Mappers
{
    internal class DietMapper : IMapper<Diet, DietDto>, IMapper<DietDto, Diet>, IMapper<CreateDietRequest, CreateDietDto>, IMapper<CreateDietDto, DietDto>
    {
        public Diet Map(DietDto input)
        {
            return new Diet
            {
                Id = input.Id,
                UserId = input.UserId,
                Name = input.Name,
                CreatedAt = input.CreatedAt,
                UpdatedAt = input.UpdatedAt
            };
        }

        public DietDto Map(Diet input)
        {
            return new DietDto
            {
                Id = input.Id,
                UserId = input.UserId,
                Name = input.Name,
                CreatedAt = input.CreatedAt,
                UpdatedAt = input.UpdatedAt
            };
        }

        public CreateDietDto Map(CreateDietRequest input)
        {
            return new CreateDietDto
            {
                //TODO: set UserId from the manager
                Name = input.Name
            };
        }

        public DietDto Map(CreateDietDto input)
        {
            return new DietDto
            {
                Id = 0, // Assuming Id is autogenerated
                UserId = input.UserId,
                Name = input.Name,
                CreatedAt = DateTime.UtcNow,
            };
        }
    }
}
